### PR TITLE
Allow using a custom image for pvc-transfer

### PR DESCRIPTION
**Pull request by jmontleon**
Addresses https://github.com/konveyor/crane/issues/116

### CODE REVIEW

**Comment by jmontleon** [comment]
Depends on https://github.com/backube/pvc-transfer/pull/26

**Review by djzager — COMMENTED** [review]
Looks good to me, just need to wait for the backube changes.

**Comment by jmontleon** [comment]
@djzager are you OK if I remove the do-not-merge/hold  label?

**Comment by djzager** [comment]
My bad @jmontleon, meant to drop that label.

**Pull request merged**
